# Generated by Django 5.1.3 on 2024-12-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_borrowingrecord_requested_changes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowingrecord",
            name="user_request_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=100,
            ),
        ),
    ]
